### PR TITLE
Fixed layout issue when changing contentSize while keyboard is shown.

### PR DESCRIPTION
**Pull request by DominicMDev**
Let me know if you have any questions about this request.

### CODE REVIEW

**Comment by kevin0571** [comment]
This should be fixed in 1.8.4

**Comment by DominicMDev** [comment]
This is not fixed in 1.8.4; here is an example of what is happening now.
example

**Comment by DominicMDev** [comment]
Here is an example of what happens when I add my changes to version 1.8.4
example1

**Comment by JettF** [comment]
I am running into this same issue.

**Comment by kevin0571** [comment]
I've pushed 1.8.5 to fix the issue you mentioned.

**Pull request closed without merging**
